quiz/urls.py
from django.urls import path
from .views import (
    QuizCreatView,
    QuizListView,
)

from quiz import views



app_name = 'quiz'

urlpatterns = [
    path('', views.homepage, name='home'),
    path('create-quiz', QuizCreatView.as_view(), name='create-quiz'),
    path('quiz-list',QuizListView.as_view(), name='quiz-list'),
    path('<pk>/', views.quiz_view, name='quiz-view'),
    path('show-quizes', views.display_quiz, name='show-quizes'),
    path('leaderboard', views.leaderboard, name='leaderboard'),
    path('attemp-quiz', views.attemp_quiz, name='attemp-quiz'),
    path('test-result', views.test_result, name='test-result'),
]

shotgun/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from shotgun import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quiz.urls', namespace='quiz'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
                                                                                         document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.




class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.IntegerField(blank=True)
    location = models.CharField(max_length=250, blank=True)
    profile_pic = models.ImageField(blank=True, null=True, upload_to='student_profile')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return super().__str__(User)

quiz/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


# QUIZ_QUESTION_TYPE = (
#     ('SINGLE CORRECT', 'Single Correct'),
#     ('TRUE OR FALSE', 'True or False'),
#     ('SUBJECTIVE', 'Subjective'),
#     ('MULTIPLE CORRECT', 'Multiple Correct'),
# )


# class Quiz(models.Model):
#     quiz_name = models.CharField(max_length=250)
#     quiz_image = models.ImageField(blank=True, upload_to='quiz_profile')
#     quiz_description = models.CharField(max_length=300, blank=True)
#     quiz_timer = models.TimeField(blank=True, null=True, help_text="Define time on each question")
#     no_of_participant = models.IntegerField(help_text="How Many Users can Participate in this quiz")
#     # participants = models.ManyToManyRel(User, related_name= 'participants')
#     created_at = models.DateTimeField(auto_now_add=True)

#     def __str__(self):
#         return f"{self.quiz_name}"
    
#     def get_questions(self):
#         return self.question_set.all()


# class Question(models.Model):
#     quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
#     question = models.CharField(max_length=250)
#     desciption = models.CharField(max_length=300, blank=True)
#     question_media = models.FileField(upload_to='quiz/question_media', blank=True)
#     question_type = models.CharField(max_length=50, choices=QUIZ_QUESTION_TYPE)
#     time_limit = models.PositiveSmallIntegerField(default=60, help_text='By Default Question timer is set for 60 seconds', blank=True) # in second
#     created_at = models.DateTimeField(auto_now_add=True)

#     def __str__(self):
#         return str(self.question)

#     def get_answers(self):
#         return self.question.all()


# class SingleChoice(models.Model):
#     question = models.OneToOneField(Question, on_delete=models.CASCADE, related_name='singlechoice')
#     text = models.TextField()
#     is_correct = models.BooleanField(default=False)
#     created_at = models.DateTimeField(auto_now_add=True)

#     def __str__(self):
#         return f"Question: {self.question}, answer: {self.text} correct:{self.is_correct}"



# class MultipleChoice(models.Model):
#     question = models.OneToOneField(Question, on_delete=models.CASCADE, related_name='mulitplechoice')
#     text = models.TextField()
#     is_correct = models.BooleanField(default=False)




# class TrueFalseQuestion(models.Model):
#     question = models.OneToOneField(Question, on_delete=models.CASCADE, related_name='true_false_question')
#     is_true = models.BooleanField(default=False)



# class SubjectiveAnswer(models.Model):
#     question = models.OneToOneField(Question, on_delete=models.CASCADE, related_name='subjective_answer')
#     answer = models.TextField()



# class PollOption(models.Model):
#     question = models.ForeignKey(Question, on_delete=models.CASCADE)
#     text = models.TextField()
#     votes = models.PositiveIntegerField(default=0)






    


"""
============================================================================================================================
"""
class QuizLevel(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=250, blank=True)
    is_active = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name}"




class Quiz(models.Model):
    level = models.ForeignKey(QuizLevel, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    topic = models.CharField(max_length=200)
    quiz_thumbnail = models.ImageField(blank=True, null=True, upload_to='quiz_thumbnail')
    required_score_to_pass = models.IntegerField(help_text="Required Score to Pass the Exam")
    no_of_participants = models.IntegerField(blank=True, null=True)
    no_of_questions = models.IntegerField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return f"{self.name}"
    

    def get_questions(self):
        return self.question_set.all()



class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    question_media = models.FileField(upload_to='quiz/question_media', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.text
    
    def get_answers(self):
        return self.answer_set.all()


class Answer(models.Model):
    text = models.CharField(max_length=200)
    correct = models.BooleanField(default=False)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return f"question: {self.question.text} answer: {self.text} correct: {self.correct}"
    



class Result(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.FloatField()

    def __str__(self):
        return str(self.pk)

accounts/views.py
from django.shortcuts import render

# Create your views here.


    

quiz/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView
from .models import Quiz, Question

# Create your views here.



class QuizCreatView(CreateView):
    model = Quiz
    template_name = 'quiz/create_quiz.html'
    fields = '__all__'
    success_url = '/quiz-list'

class QuizListView(ListView):
    model = Quiz
    template_name = 'quiz/list_quiz.html'


def quiz_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)

    questions = Question.objects.filter(quiz=quiz)
    
    return render(request, "quiz/quiz_view.html", {'obj':quiz, 'questions': questions,})




def homepage(request):
    return render(request, "quiz/homepage.html")



def display_quiz(request):
    return render(request, "quiz/display_quiz.html")


def leaderboard(request):
    return render(request, "quiz/leaderboard.html")


def attemp_quiz(request):
    return render(request, "quiz/attemp_quiz.html")



def test_result(request): #This will show result right after the test submission
    return render(request, "quiz/test_result.html")

quiz/templates/quiz/attemp_quiz.html
{% extends 'quiz/base.html' %}
{% load static %}
{% block custom_css %}
<link rel="stylesheet" href="{% static 'quiz/css/attemp_quiz.css' %}">
{% endblock custom_css %}

{% block page_title %}
quiz
{% endblock page_title %}


{% block page_content %}

<div class="container attemp-quiz">
        <div class="question-body">
            <h2>Which of the following is correct??</h2>
            <div class="question-media">
                <img src="{% static 'quiz/images/dataset-cover.png' %}" style="width:500px" alt="...">
            </div>
        </div>
        <div class="option-body">
            <div class="option1">
                <h4>London</h4>
            </div>
            <div class="option2">
                India
            </div>
            <div class="option3">
                Japan
            </div>
            <div class="option4">
                Germany
            </div>
            <a href="{% url 'quiz:test-result' %}" class="btn btn-primary">Submit</a>
        </div>
</div>
{% endblock page_content %}

quiz/templates/quiz/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block page_title %}{% endblock page_title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/fontawesome.min.css" integrity="sha512-giQeaPns4lQTBMRpOOHsYnGw1tGVzbAIHUyHRgn7+6FmiEgGGjaG0T2LZJmAPMzRCl+Cug0ItQ2xDZpTmEc+CQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/brands.min.css" integrity="sha512-G/T7HQJXSeNV7mKMXeJKlYNJ0jrs8RsWzYG7rVACye+qrcUhEAYKYzaa+VFy6eFzM2+/JT1Q+eqBbZFSHmJQew==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'quiz/css/quiz.css' %}">
    {% block custom_css %}{% endblock custom_css %}
  </head>
  <body>
    {% include 'quiz/navbar.html' %}
    {% block page_heading %}
    
    {% endblock page_heading %}
    
    {% block page_content %}

    {% endblock page_content %}

    {% block custom_js %}
    {% endblock custom_js %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
  </body>
</html>

quiz/templates/quiz/create_quiz.html
<form method="POST" enctype="multipart/form-data">

	<!-- Security token -->
	{% csrf_token %}

	<!-- Using the formset -->
	{{ form.as_p }}
	
	<input type="submit" value="Submit">
</form>

quiz/templates/quiz/display_quiz.html
{% extends 'quiz/base.html' %}
{% load static %}
{% block page_title %}
Quizes

{% endblock page_title %}


{% block page_content %}
<div class="container">
    <div class="card shadow mt-5" style="width: 18rem;">
        <img src="{% static 'quiz/images/dataset-cover.png' %}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Bollywood Quiz</h5>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          <a href="{% url 'quiz:attemp-quiz' %}" class="btn btn-primary">Start</a>
          <a href="#" class="btn btn-secondary">Share</a>
        </div>
      </div>
</div>


{% endblock page_content %}

quiz/templates/quiz/homepage.html
{% extends 'quiz/base.html' %}
{% load static %}
{% block custom_css %}

{% endblock custom_css %}


{% block page_title %}
Home
{% endblock page_title %}


{% block page_content %}
<div class="container col-xl-10 col-xxl-8 px-4 py-5 hero">
    <div class="row align-items-center g-lg-5 py-5">
      <div class="col-lg-7 text-center text-lg-start">
        <h1 class="display-4 fw-bold lh-1 mb-3">Vertically centered hero sign-up form</h1>
        <p class="col-lg-10 fs-4">Below is an example form built entirely with Bootstrap’s form controls. Each required form group has a validation state that can be triggered by attempting to submit the form without completing it.</p>
      </div>
      <div class="col-md-10 mx-auto col-lg-5">
        <form class="p-4 p-md-5 border rounded-3 bg-light">
          <div class="form-floating mb-3">
            <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
            <label for="floatingInput">Email address</label>
          </div>
          <div class="form-floating mb-3">
            <input type="password" class="form-control" id="floatingPassword" placeholder="Password">
            <label for="floatingPassword">Password</label>
          </div>
          <div class="checkbox mb-3">
            <label>
              <input type="checkbox" value="remember-me"> Remember me
            </label>
          </div>
          <button class="w-100 btn btn-lg btn-primary" type="submit">Sign up</button>
          <hr class="my-4">
          <small class="text-muted">By clicking Sign up, you agree to the terms of use.</small>
        </form>
      </div>
    </div>
  </div>

{% endblock page_content %}

quiz/templates/quiz/leaderboard.html
{% extends 'quiz/base.html' %}

{% load static %}
{% block page_title %}Leaderboard{% endblock page_title %}


{% block page_content %}
<div class="container">
    <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Rank</th>
            <th scope="col">Profile</th>
            <th scope="col">Name</th>
            <th scope="col">Level</th>
            <th scope="col">Score</th>
            <th scope="col">Location</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row">1</th>
            <td>1</td>
            <td><img src="{% static 'quiz\images\undraw_male_avatar_g98d.svg' %}" style="width:50px" alt=""></td>
            <td>Vishal Vishwakarma</td>
            <td>Level 5</td>
            <td>55000</td>
            <td>Kanpur</td>
          </tr>
          <tr>
            <th scope="row">2</th>
            <td>1</td>
            <td><img src="{% static 'quiz\images\undraw_male_avatar_g98d.svg' %}" style="width:50px" alt=""></td>
            <td>Vishal Vishwakarma</td>
            <td>Level 5</td>
            <td>55000</td>
            <td>Kanpur</td>
          </tr>
          <tr>
            <th scope="row">3</th>
            <td>1</td>
            <td><img src="{% static 'quiz\images\undraw_male_avatar_g98d.svg' %}" style="width:50px" alt=""></td>
            <td>Vishal Vishwakarma</td>
            <td>Level 5</td>
            <td>55000</td>
            <td>Kanpur</td>
          </tr>
        </tbody>
      </table>
</div>


{% endblock page_content %}

quiz/templates/quiz/list_quiz.html
{% extends 'quiz/base.html' %}
{% load static %}

{% block custom_css %}

<style>
.custom_card{
  display: flex;
  justify-content: space-between;
  align-items: center;
}
</style>

{% endblock custom_css %}


{% block page_title %}
quiz
{% endblock page_title %}



{% block custom_js %}

<script src="{% static 'quiz/js/quiz.js' %}" defer></script>

{% endblock custom_js %}


{% block page_heading %}
<div class="container mt-5">
  <nav>
    <ul class="nav nav-pills nav-fill gap-2 p-1 small bg-primary rounded-5 shadow-sm" id="pillNav2" role="tablist" style="--bs-nav-link-color: var(--bs-white); --bs-nav-pills-link-active-color: var(--bs-primary); --bs-nav-pills-link-active-bg: var(--bs-white);">
      <li class="nav-item" role="presentation">
        <button class="nav-link active rounded-5" id="home-tab2" data-bs-toggle="tab" type="button" role="tab" aria-selected="true">Home</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link rounded-5" id="profile-tab2" data-bs-toggle="tab" type="button" role="tab" aria-selected="false">Profile</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link rounded-5" id="contact-tab2" data-bs-toggle="tab" type="button" role="tab" aria-selected="false">Contact</button>
      </li>
    </ul>
  </nav>
</div>
{% endblock page_heading %}


{% block page_content %}



<div class="container mt-5">
  {% for obj in object_list %}
  <div class="row shadow p-3 mb-5 bg-body-tertiary align-items-center">
    <div class="col-sm-2">
      <div class="quiz-thumbnail">
        <img src="{{ obj.quiz_thumbnail.url }}" style="width: 176px;
        height: 120px" alt="quiz-thumbnail">
      </div>
    </div> 
    <div class="col-sm-8">
      <h4>{{obj.name}}</h4>
      <p>Level: {{obj.level}}</p>
      <p>No. of Participant - {{obj.no_of_participants}}</p>
    </div> 
    <div class="col-sm-2">
      <a href="{% url 'quiz:quiz-view' pk=obj.pk %}" class="btn btn-primary">View Quiz</a> <br>
      <span>Last Update at: {{obj.updated_at}}</span>
    </div> 
  </div>
  {% endfor %}
</div>



{% endblock page_content %}

quiz/templates/quiz/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg ml-auto">
    <div class="container-fluid">
      <a class="navbar-brand" href="/"><img src="{% static 'quiz/images/logo.png' %}" style="width:150px" alt=""></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'quiz:show-quizes' %}">Quizes</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'quiz:leaderboard' %}">Leaderboard</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Contact Us</a>
          </li>
      </div>
    </div>
  </nav>

quiz/templates/quiz/quiz_detail.html
{% extends 'quiz/base.html' %}


{% block page_title %}
title
{% endblock page_title %}


{% block page_content %}
<div class="container">
    
</div>

{% endblock page_content %}

quiz/templates/quiz/quiz_view.html
{% extends 'quiz/base.html' %}

{% block custom_css %}
<style>
.period{
    background-color: blue;
    color: #fff
}

</style>
{% endblock custom_css %}


{% block page_heading %}
<div class="container mt-5">
    <h3>Quiz Name: {{obj.name}}</h3>
</div>

{% endblock page_heading %}

{% block page_content %}
<div class="container">
    <div class="row ">
        <div class="col-lg-4 shadow p-3 mb-5 rounded">
            <img src="{{ obj.quiz_thumbnail.url }}" style="width: 100%;
        height: 248.4px" alt="quiz-thumbnail">
        <p>Level: {{obj.level}}</p>
        <h3>Quiz Name: {{obj.name}}</h3>
        <span>Topic: {{obj.topic}}</span>
        <h5>Quiz in Progress</h5>
        <div class="period">
            Ends: <i class="fa-regular fa-trophy"></i> in 2 Days
        </div>
        <div class="buttons">
            <a href="#" class="btn btn-primary mt-5">Start</a>
            <a href="#" class="btn btn-secondary mt-5">Assign</a>
        </div>
        </div>
        <div class="col-lg-8">
            <div class="container">
                <h5>Questions </h5>
            {% for question in questions %}
            <h3>{{ question.text }}</h3>
            {% for option in question.answer_set.all %}
                <input type="radio" name="{{ question.id }}" value="{{ option.id }}"> {{ option.text }}<br>
            {% endfor %}
            {% endfor %}
            </div>

        </div>
    </div>
</div>
{% endblock page_content %}

quiz/templates/quiz/test_result.html
{% extends 'quiz/base.html' %}

{% load static %}

{% block page_title %}
Result
{% endblock page_title %}


{% block page_content %}
<div class="container text-center">
    <h1>Thank you for Participating Vishal</h1>
    <img src="{% static 'quiz\images\undraw_male_avatar_g98d.svg' %}" style="width:300px" alt="">

    <h1>You have Scored 11500 points</h1>
    <h2>Your are on 15th Rank</h2>
    <a href="#" class="btn btn-warning">See your Profile</a>
</div>

{% endblock page_content %}